import type { PaletteColor, PatternCell, QuantizationMethod } from ".";

/** Serializable raw RGBA raster data in row-major pixel order. */
export interface RawRgbaImage {
  width: number;
  height: number;
  rgba: readonly number[];
}

export interface RgbColor {
  red: number;
  green: number;
  blue: number;
}

export interface QuantizeRgbOptions {
  /** Generic palette entries; no colors are generated by quantization. */
  palette: readonly PaletteColor[];
  /** Number of palette entries permitted for this quantization, from 1 through palette.length. */
  colorLimit: number;
  /** Defaults to nearest-color to preserve V1 conversion behavior. */
  method?: QuantizationMethod;
}

/** A row-major grid that can be assigned directly to PatternDocument.settings.grid and cells. */
export interface QuantizedPatternGrid {
  width: number;
  height: number;
  palette: PaletteColor[];
  cells: PatternCell[];
}

interface NormalizedPaletteColor {
  color: PaletteColor;
  rgb: RgbColor;
}

/**
 * Finds the nearest palette color using squared Euclidean RGB distance.
 * Equal distances resolve first by lower sortOrder, then lexicographically by id.
 */
export function nearestPaletteColor(rgb: RgbColor, palette: readonly PaletteColor[]): PaletteColor {
  validateRgb(rgb);
  const candidates = normalizePalette(palette);
  if (candidates.length === 0) throw new RangeError("Palette must contain at least one color.");
  return nearestNormalizedPaletteColor(rgb, candidates).color;
}

/**
 * Quantizes serializable row-major RGBA data to generic palette IDs.
 *
 * V1 transparent-pixel behavior: a pixel with alpha exactly zero maps to the
 * first allowed palette color (lowest sortOrder, then id). Partially opaque
 * pixels use their un-premultiplied RGB channels. This guarantees every cell
 * references an allowed palette ID and never introduces a synthetic color.
 */
export function quantizeRgb(image: RawRgbaImage, options: QuantizeRgbOptions): QuantizedPatternGrid {
  validateImage(image);
  const allowedPalette = normalizePalette(options?.palette);
  validatePatternPalette(allowedPalette);
  validateColorLimit(options?.colorLimit, allowedPalette.length);
  const palette = allowedPalette.slice(0, options.colorLimit);
  const method = options.method ?? "nearest-color";
  validateQuantizationMethod(method);
  const cells = method === "floyd-steinberg"
    ? quantizeFloydSteinberg(image, palette)
    : quantizeNearestColor(image, palette);

  return { width: image.width, height: image.height, palette: palette.map(({ color }) => color), cells };
}

function quantizeNearestColor(image: RawRgbaImage, palette: readonly NormalizedPaletteColor[]): PatternCell[] {
  const cells: PatternCell[] = [];
  for (let offset = 0; offset < image.rgba.length; offset += 4) {
    const red = image.rgba[offset];
    const green = image.rgba[offset + 1];
    const blue = image.rgba[offset + 2];
    const alpha = image.rgba[offset + 3];
    const color = alpha === 0
      ? palette[0]
      : nearestNormalizedPaletteColor({ red, green, blue }, palette);
    cells.push({ paletteColorId: color.color.id });
  }
  return cells;
}

/** Applies the standard left-to-right Floyd-Steinberg kernel in row-major order. */
function quantizeFloydSteinberg(image: RawRgbaImage, palette: readonly NormalizedPaletteColor[]): PatternCell[] {
  const pixelCount = image.width * image.height;
  const channels = new Float64Array(pixelCount * 3);
  const cells: PatternCell[] = [];
  for (let index = 0; index < pixelCount; index += 1) {
    const rgbaOffset = index * 4;
    const channelOffset = index * 3;
    channels[channelOffset] = image.rgba[rgbaOffset];
    channels[channelOffset + 1] = image.rgba[rgbaOffset + 1];
    channels[channelOffset + 2] = image.rgba[rgbaOffset + 2];
  }
  for (let y = 0; y < image.height; y += 1) {
    for (let x = 0; x < image.width; x += 1) {
      const index = y * image.width + x;
      const rgbaOffset = index * 4;
      if (image.rgba[rgbaOffset + 3] === 0) {
        cells.push({ paletteColorId: palette[0].color.id });
        continue;
      }
      const channelOffset = index * 3;
      const rgb = { red: channels[channelOffset], green: channels[channelOffset + 1], blue: channels[channelOffset + 2] };
      const color = nearestNormalizedPaletteColor(rgb, palette);
      cells.push({ paletteColorId: color.color.id });
      const error = { red: rgb.red - color.rgb.red, green: rgb.green - color.rgb.green, blue: rgb.blue - color.rgb.blue };
      diffuseError(x + 1, y, 7 / 16, image, channels, error);
      diffuseError(x - 1, y + 1, 3 / 16, image, channels, error);
      diffuseError(x, y + 1, 5 / 16, image, channels, error);
      diffuseError(x + 1, y + 1, 1 / 16, image, channels, error);
    }
  }
  return cells;
}

function diffuseError(x: number, y: number, weight: number, image: RawRgbaImage, channels: Float64Array, error: RgbColor): void {
  if (x < 0 || x >= image.width || y < 0 || y >= image.height) return;
  const pixelIndex = y * image.width + x;
  if (image.rgba[pixelIndex * 4 + 3] === 0) return;
  const channelOffset = pixelIndex * 3;
  channels[channelOffset] += error.red * weight;
  channels[channelOffset + 1] += error.green * weight;
  channels[channelOffset + 2] += error.blue * weight;
}

function normalizePalette(palette: unknown): NormalizedPaletteColor[] {
  if (!Array.isArray(palette)) throw new RangeError("Palette must be an array of colors.");

  const ids = new Set<string>();
  const result: NormalizedPaletteColor[] = [];
  for (const color of palette) {
    if (!color || typeof color !== "object" || typeof color.id !== "string" || !color.id.trim() || ids.has(color.id)) {
      throw new RangeError("Palette colors must have unique non-empty IDs.");
    }
    if (typeof color.name !== "string" || !color.name.trim()) {
      throw new RangeError("Palette colors must have non-empty generic names.");
    }
    if (!Number.isSafeInteger(color.sortOrder) || color.sortOrder < 0) {
      throw new RangeError("Palette color sortOrder values must be non-negative safe integers.");
    }
    const hex = color.hex;
    if (typeof hex !== "string") {
      throw new RangeError("Palette colors must use uppercase #RRGGBB hex values.");
    }
    result.push({ color, rgb: parseHexRgb(hex) });
    ids.add(color.id);
  }
  result.sort((left, right) => left.color.sortOrder - right.color.sortOrder || compareIds(left.color.id, right.color.id));
  return result;
}

function nearestNormalizedPaletteColor(rgb: RgbColor, palette: readonly NormalizedPaletteColor[]): NormalizedPaletteColor {
  let nearest = palette[0];
  let nearestDistance = squaredRgbDistance(rgb, nearest.rgb);
  for (let index = 1; index < palette.length; index += 1) {
    const candidate = palette[index];
    const distance = squaredRgbDistance(rgb, candidate.rgb);
    if (distance < nearestDistance) {
      nearest = candidate;
      nearestDistance = distance;
    }
  }
  return nearest;
}

function validatePatternPalette(palette: readonly NormalizedPaletteColor[]): void {
  if (palette.length === 0) throw new RangeError("Palette must contain at least one color.");
}

function validateColorLimit(colorLimit: unknown, paletteLength: number): asserts colorLimit is number {
  if (typeof colorLimit !== "number" || !Number.isSafeInteger(colorLimit) || colorLimit < 1 || colorLimit > paletteLength) {
    throw new RangeError("colorLimit must be a positive safe integer no greater than the palette length.");
  }
}

function validateQuantizationMethod(method: unknown): asserts method is QuantizationMethod {
  if (method !== "nearest-color" && method !== "floyd-steinberg") {
    throw new RangeError("Unsupported quantization method.");
  }
}

function compareIds(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function parseHexRgb(hex: string): RgbColor {
  if (!/^#[0-9A-F]{6}$/.test(hex)) throw new RangeError("Palette colors must use uppercase #RRGGBB hex values.");
  return {
    red: Number.parseInt(hex.slice(1, 3), 16),
    green: Number.parseInt(hex.slice(3, 5), 16),
    blue: Number.parseInt(hex.slice(5, 7), 16),
  };
}

function squaredRgbDistance(left: RgbColor, right: RgbColor): number {
  return (left.red - right.red) ** 2 + (left.green - right.green) ** 2 + (left.blue - right.blue) ** 2;
}

function validateRgb(rgb: RgbColor): void {
  if (!rgb || typeof rgb !== "object") throw new RangeError("RGB channels must be integers from 0 through 255.");
  for (const channel of [rgb.red, rgb.green, rgb.blue]) {
    if (!Number.isInteger(channel) || channel < 0 || channel > 255) {
      throw new RangeError("RGB channels must be integers from 0 through 255.");
    }
  }
}

function validateImage(image: RawRgbaImage): void {
  if (!image || typeof image !== "object" || !Number.isSafeInteger(image.width) || image.width < 1 || !Number.isSafeInteger(image.height) || image.height < 1 || image.width > Number.MAX_SAFE_INTEGER / image.height / 4) {
    throw new RangeError("Image dimensions must be positive safe integers.");
  }
  if (!Array.isArray(image.rgba) || image.rgba.length !== image.width * image.height * 4) {
    throw new RangeError("RGBA data length must equal width × height × 4.");
  }
  for (const channel of image.rgba) {
    if (!Number.isInteger(channel) || channel < 0 || channel > 255) {
      throw new RangeError("RGBA channels must be integers from 0 through 255.");
    }
  }
}
